[package]
name = "ruuvitag-listener"
description = "Print RuuviTag measurements in Telegraf compatible format"
version = "0.5.4"
license = "MIT"
authors = ["Ville Lautanala <lautis@gmail.com>"]
repository = "https://github.com/lautis/ruuvitag-listener"
keywords = ["ruuvi", "ruuvitag", "telegraf"]
edition = "2018"

[dependencies]
btleplug = "0.5.*"
ruuvi-sensor-protocol = "0.4.*"
structopt = { version = "0.3.*", default-features = false }

[profile.release]
opt-level = "s"
lto = true
panic = "abort"
